namespace MathMLToLaTex.Helpers;

public static class UTF8ToLtXConverter
{

    public static string Convert(string t) => char.IsLetterOrDigit(t, 0)
            ? t
            : (VowelsWithAccents.TryGetValue(t, out var v)
            ? (AccentToLTXCmd.TryGetValue(v.accent, out var cmd) ? cmd : $"\\{cmd}{{{v.vowel}}}")
            : (SpecialFontChars.TryGetValue(t, out var sf))
            ? $"\\{sf.letter}{{{sf.fontcmd}}}"
            : t)
            ;

    public static readonly char[] LatexAccentLetters =  [
            'a'
         , 'e'
         , 'i'
         , 'o'
         , 'u'
         , 'y'
         , 'A'
         , 'E'
         , 'I'
         , 'O'
         , 'U'
         , 'Y'
         , 'n'
         , 'N'
         , 'c'
         , 'C'
         , 'v'
         , 'V'
         , 'j'
         , 'J'
         , 'z'
         , 'Z'
    ];
    public static readonly char[] LatexAccentChars = [
         '´' , '`' , '^' , '~' , '¨' , 'ˆ' , '˚' , '˙' , '˘' , '˝' , 'ˇ' , 'ˆ' , '˜' , '-'
        ];
    public static readonly string[] LateXAccentCMD =  [
            "acute"
          , "grave"
          , "hat"
          , "tilde"
          , "ddot"
          , "breve"
          , "check"
          , "dot"
          , "mathring"
          , "bar"
          , "vec"
        ];

    public static readonly Dictionary<string, string> AccentToLTXCmd = new()
    {
        ["´"] = "grave",
        ["`"] = "acute",
        ["^"] = "hat",
        ["~"] = "tilde",
        ["¨"] = "ddot",
        ["˚"] = "mathring",
        ["˘"] = "breve",
        ["ˇ"] = "check",
        ["˝"] = "ddot",
        ["˙"] = "dot",
        ["-"] = "bar",
        ["ˆ"] = "hat",
        ["˜"] = "tilde",

    };
    public static readonly string[] LTXFontCmds = [ "mathbf" , "mathit" , "mathbb" , "mathcal" , "mathfrak" , "mathsf" , "mathtt"];
    public static readonly string[] UppercaseLetter =  [
      "A",
      "B",
      "C",
      "D",
      "E",
      "F",
      "G",
      "H",
      "I",
      "J",
      "K",
      "L",
      "M",
      "N",
      "O",
      "P",
      "Q",
      "R",
      "S",
      "T",
      "U",
      "V",
      "W",
      "X",
      "Y",
      "Z",
      "\\Beta",
      "\\Gamma",
      "\\Delta",
      "\\Theta",
      "\\Lambda",
      "\\Xi",
      "\\Pi",
      "\\Sigma",
      "\\Upsilon",
      "\\Phi",
      "\\Psi",
      "\\Omega",
      "0",
      "1",
      "2",
      "3",
      "4",
      "5",
      "6",
      "7",
      "8",
      "9"];
    public static readonly Dictionary<string, (string vowel, string accent)> VowelsWithAccents = new()
    {
        ["á"] = ("a", "´"),
        ["à"] = ("a", "`"),
        ["â"] = ("a", "^"),
        ["ã"] = ("a", "~"),
        ["ä"] = ("a", "¨"),
        ["å"] = ("a", "˚"),
        ["ą"] = ("a", "˙"),
        ["ă"] = ("a", "˘"),
        ["ǎ"] = ("a", "ˇ"),
        ["ǟ"] = ("a", "ˆ"),
        ["ǻ"] = ("a", "˙"),
        ["ǡ"] = ("a", "-"),
        ["ā"] = ("a", "-"),
        ["é"] = ("e", "´"),
        ["è"] = ("e", "`"),
        ["ê"] = ("e", "^"),
        ["ë"] = ("e", "¨"),
        ["ę"] = ("e", "˙"),
        ["ě"] = ("e", "ˇ"),
        ["ȇ"] = ("i", "^"),
        ["ё"] = ("'", "'"),
        ["ē"] = ("e", "-"),
        ["í"] = ("i", "´"),
        ["ì"] = ("i", "`"),
        ["î"] = ("i", "^"),
        ["ï"] = ("i", "¨"),
        ["į"] = ("i", "˙"),
        ["ǐ"] = ("i", "ˇ"),
        ["ȉ"] = ("i", "`"),
        ["ȋ"] = ("i", "¨"),
        ["ī"] = ("i", "-"),
        ["ó"] = ("o", "´"),
        ["ò"] = ("o", "`"),
        ["ô"] = ("o", "^"),
        ["õ"] = ("o", "~"),
        ["ö"] = ("o", "¨"),
        ["ő"] = ("o", "˝"),
        ["ǒ"] = ("o", "ˇ"),
        ["ȍ"] = ("o", "`"),
        ["ȏ"] = ("o", "¨"),
        ["ȫ"] = ("o", "˘"),
        ["ȭ"] = ("o", "˝"),
        ["ȯ"] = ("o", "˙"),
        ["ō"] = ("o", "-"),
        ["ú"] = ("u", "´"),
        ["ù"] = ("u", "`"),
        ["û"] = ("u", "^"),
        ["ü"] = ("u", "¨"),
        ["ű"] = ("u", "˝"),
        ["ǔ"] = ("u", "ˇ"),
        ["ǖ"] = ("u", "¨"),
        ["ǘ"] = ("u", "¨"),
        ["ǚ"] = ("u", "¨"),
        ["ǜ"] = ("u", "¨"),
        ["ȕ"] = ("u", "`"),
        ["ȗ"] = ("u", "¨"),
        ["ū"] = ("u", "-"),
        ["ý"] = ("y", "´"),
        ["ỳ"] = ("y", "`"),
        ["ŷ"] = ("y", "^"),
        ["ÿ"] = ("y", "¨"),
        ["ȳ"] = ("y", "-"),
        ["Á"] = ("A", "´"),
        ["À"] = ("A", "`"),
        ["Â"] = ("A", "^"),
        ["Ã"] = ("A", "~"),
        ["Ä"] = ("A", "¨"),
        ["Å"] = ("A", "˚"),
        ["Å"] = ("'", "'"),
        ["Ȧ"] = ("A", "˙"),
        ["Ă"] = ("A", "˘"),
        ["Ǎ"] = ("A", "ˇ"),
        ["Ǟ"] = ("A", "˝"),
        ["Ǻ"] = ("A", "˚"),
        ["Ǡ"] = ("A", "-"),
        ["Ā"] = ("A", "-"),
        ["É"] = ("E", "´"),
        ["È"] = ("E", "`"),
        ["Ė"] = ("E", "˙"),
        ["Ê"] = ("E", "^"),
        ["Ë"] = ("E", "¨"),
        ["Ě"] = ("E", "ˇ"),
        ["Ȅ"] = ("E", "`"),
        ["Ȇ"] = ("E", "¨"),
        ["Ē"] = ("E", "-"),
        ["Í"] = ("I", "´"),
        ["Ì"] = ("I", "`"),
        ["Î"] = ("I", "^"),
        ["Ï"] = ("I", "¨"),
        ["Ĭ"] = ("I", "˘"),
        ["Ǐ"] = ("I", "ˇ"),
        ["Ȉ"] = ("I", "`"),
        ["Ȋ"] = ("I", "¨"),
        ["Ī"] = ("I", "-"),
        ["Ó"] = ("O", "´"),
        ["Ò"] = ("O", "`"),
        ["Ô"] = ("O", "^"),
        ["Õ"] = ("O", "~"),
        ["Ö"] = ("O", "¨"),
        ["Ő"] = ("O", "˝"),
        ["Ǒ"] = ("O", "ˇ"),
        ["Ȍ"] = ("O", "`"),
        ["Ȏ"] = ("O", "¨"),
        ["Ȫ"] = ("O", "˘"),
        ["Ȭ"] = ("O", "˝"),
        ["Ȯ"] = ("O", "˙"),
        ["Ō"] = ("O", "-"),
        ["Ú"] = ("U", "´"),
        ["Ù"] = ("U", "`"),
        ["Û"] = ("U", "^"),
        ["Ü"] = ("U", "¨"),
        ["Ű"] = ("U", "˝"),
        ["Ǔ"] = ("U", "ˇ"),
        ["Ǖ"] = ("U", "¨"),
        ["Ȕ"] = ("U", "`"),
        ["Ȗ"] = ("U", "¨"),
        ["Ū"] = ("U", "-"),
        ["Ý"] = ("Y", "´"),
        ["Ỳ"] = ("Y", "`"),
        ["Ŷ"] = ("Y", "^"),
        ["Ÿ"] = ("Y", "¨"),
        ["Ȳ"] = ("Y", "-"),
        ["ñ"] = ("n", "~"),
        ["Ñ"] = ("N", "~"),
        ["ç"] = ("c", "˙"),
        ["Ç"] = ("C", "˙"),
        ["ṽ"] = ("v", "~"),
        ["Ṽ"] = ("V", "~"),
        ["ĵ"] = ("j", "^"),
        ["Ĵ"] = ("J", "^"),
        ["ź"] = ("z", "´"),
        ["Ź"] = ("Z", "´"),
        ["Ż"] = ("Z", "^"),
        ["ż"] = ("z", "^"),
        ["Ž"] = ("Z", "ˇ"),
        ["ž"] = ("z", "ˇ"),
        ["ẑ"] = ("z", "ˆ"),
    };
    public static readonly Dictionary<string, (string letter, string fontcmd)> SpecialFontChars = new()
    {
        ["𝐀"] = ("A", "mathbf"),
        ["𝐁"] = ("B", "mathbf"),
        ["𝐂"] = ("C", "mathbf"),
        ["𝐃"] = ("D", "mathbf"),
        ["𝐄"] = ("E", "mathbf"),
        ["Ε"] = ("E", "mathbf"),
        ["𝐅"] = ("F", "mathbf"),
        ["𝐆"] = ("G", "mathbf"),
        ["𝐇"] = ("H", "mathbf"),
        ["𝐈"] = ("I", "mathbf"),
        ["𝐉"] = ("J", "mathbf"),
        ["𝐊"] = ("K", "mathbf"),
        ["𝐋"] = ("L", "mathbf"),
        ["𝐌"] = ("M", "mathbf"),
        ["𝐍"] = ("N", "mathbf"),
        ["𝐎"] = ("O", "mathbf"),
        ["𝐏"] = ("P", "mathbf"),
        ["𝐐"] = ("Q", "mathbf"),
        ["𝐑"] = ("R", "mathbf"),
        ["𝐒"] = ("S", "mathbf"),
        ["𝐓"] = ("T", "mathbf"),
        ["𝐔"] = ("U", "mathbf"),
        ["𝐕"] = ("V", "mathbf"),
        ["𝐖"] = ("W", "mathbf"),
        ["𝐗"] = ("X", "mathbf"),
        ["𝞆"] = ("X", "mathbf"),
        ["𝐘"] = ("Y", "mathbf"),
        ["𝐙"] = ("Z", "mathbf"),
        ["𝟎"] = ("0", "mathbf"),
        ["𝟏"] = ("1", "mathbf"),
        ["𝟐"] = ("2", "mathbf"),
        ["𝟑"] = ("3", "mathbf"),
        ["𝟒"] = ("4", "mathbf"),
        ["𝟓"] = ("5", "mathbf"),
        ["𝟔"] = ("6", "mathbf"),
        ["𝟕"] = ("7", "mathbf"),
        ["𝟖"] = ("8", "mathbf"),
        ["𝟗"] = ("9", "mathbf"),
        ["𝐴"] = ("A", "mathit"),
        ["𝐵"] = ("B", "mathit"),
        ["𝐶"] = ("C", "mathit"),
        ["𝐷"] = ("D", "mathit"),
        ["𝐸"] = ("E", "mathit"),
        ["𝐹"] = ("F", "mathit"),
        ["𝐺"] = ("G", "mathit"),
        ["𝐻"] = ("H", "mathit"),
        ["𝐼"] = ("I", "mathit"),
        ["Ι"] = ("I", "mathit"),
        ["𝐽"] = ("J", "mathit"),
        ["𝐾"] = ("K", "mathit"),
        ["𝐿"] = ("L", "mathit"),
        ["𝑀"] = ("M", "mathit"),
        ["𝑁"] = ("N", "mathit"),
        ["𝑂"] = ("O", "mathit"),
        ["𝑃"] = ("P", "mathit"),
        ["𝑄"] = ("Q", "mathit"),
        ["𝑅"] = ("R", "mathit"),
        ["𝑆"] = ("S", "mathit"),
        ["𝑇"] = ("T", "mathit"),
        ["𝑈"] = ("U", "mathit"),
        ["𝑉"] = ("V", "mathit"),
        ["𝑊"] = ("W", "mathit"),
        ["𝑋"] = ("X", "mathit"),
        ["𝑌"] = ("Y", "mathit"),
        ["𝑍"] = ("Z", "mathit"),
        ["𝔸"] = ("A", "mathbb"),
        ["𝔹"] = ("B", "mathbb"),
        ["ℂ"] = ("C", "mathbb"),
        ["𝔻"] = ("D", "mathbb"),
        ["𝔼"] = ("E", "mathbb"),
        ["𝔽"] = ("F", "mathbb"),
        ["𝔾"] = ("G", "mathbb"),
        ["ℍ"] = ("H", "mathbb"),
        ["𝕀"] = ("I", "mathbb"),
        ["𝕁"] = ("J", "mathbb"),
        ["𝕂"] = ("K", "mathbb"),
        ["𝕃"] = ("L", "mathbb"),
        ["𝕄"] = ("M", "mathbb"),
        ["ℕ"] = ("N", "mathbb"),
        ["𝕆"] = ("O", "mathbb"),
        ["ℙ"] = ("P", "mathbb"),
        ["ℚ"] = ("Q", "mathbb"),
        ["ℝ"] = ("R", "mathbb"),
        ["𝕊"] = ("S", "mathbb"),
        ["𝕋"] = ("T", "mathbb"),
        ["𝕌"] = ("U", "mathbb"),
        ["𝕍"] = ("V", "mathbb"),
        ["𝕎"] = ("W", "mathbb"),
        ["𝕏"] = ("X", "mathbb"),
        ["𝕐"] = ("Y", "mathbb"),
        ["ℤ"] = ("Z", "mathbb"),
        ["𝟘"] = ("0", "mathbb"),
        ["𝟙"] = ("1", "mathbb"),
        ["𝟚"] = ("2", "mathbb"),
        ["𝟛"] = ("3", "mathbb"),
        ["𝟜"] = ("4", "mathbb"),
        ["𝟝"] = ("5", "mathbb"),
        ["𝟞"] = ("6", "mathbb"),
        ["𝟟"] = ("7", "mathbb"),
        ["𝟠"] = ("8", "mathbb"),
        ["𝟡"] = ("9", "mathbb"),
        ["𝒜"] = ("A", "mathca"),
        ["𝓐"] = ("A", "mathca"),
        ["ℬ"] = ("B", "mathca"),
        ["𝒞"] = ("C", "mathca"),
        ["𝒟"] = ("D", "mathca"),
        ["𝓓"] = ("D", "mathca"),
        ["ℰ"] = ("E", "mathca"),
        ["ℱ"] = ("F", "mathca"),
        ["𝓕"] = ("F", "mathca"),
        ["𝒢"] = ("G", "mathca"),
        ["ℋ"] = ("H", "mathca"),
        ["ℐ"] = ("I", "mathca"),
        ["𝒥"] = ("J", "mathca"),
        ["𝒦"] = ("K", "mathca"),
        ["ℒ"] = ("L", "mathca"),
        ["𝓛"] = ("L", "mathca"),
        ["ℳ"] = ("M", "mathca"),
        ["𝒩"] = ("N", "mathca"),
        ["𝒪"] = ("O", "mathca"),
        ["𝓞"] = ("O", "mathca"),
        ["𝒫"] = ("P", "mathca"),
        ["𝒬"] = ("Q", "mathca"),
        ["ℛ"] = ("R", "mathca"),
        ["𝕽"] = ("R", "mathca"),
        ["℟"] = ("R", "mathca"),
        ["𝒮"] = ("S", "mathca"),
        ["𝒯"] = ("T", "mathca"),
        ["𝒰"] = ("U", "mathca"),
        ["𝒱"] = ("V", "mathca"),
        ["𝒲"] = ("W", "mathca"),
        ["𝒳"] = ("X", "mathca"),
        ["𝒴"] = ("Y", "mathca"),
        ["𝒵"] = ("Z", "mathca"),
        ["𝔄"] = ("A", "mathfr"),
        ["𝔅"] = ("B", "mathfr"),
        ["ℭ"] = ("C", "mathfr"),
        ["𝔇"] = ("D", "mathfr"),
        ["𝔈"] = ("E", "mathfr"),
        ["𝔉"] = ("F", "mathfr"),
        ["𝔊"] = ("G", "mathfr"),
        ["ℌ"] = ("H", "mathfr"),
        ["ℑ"] = ("I", "mathfr"),
        ["𝔍"] = ("J", "mathfr"),
        ["𝔎"] = ("K", "mathfr"),
        ["𝔏"] = ("L", "mathfr"),
        ["𝔐"] = ("M", "mathfr"),
        ["𝔑"] = ("N", "mathfr"),
        ["𝔒"] = ("O", "mathfr"),
        ["𝔓"] = ("P", "mathfr"),
        ["𝔔"] = ("Q", "mathfr"),
        ["ℜ"] = ("R", "mathfr"),
        ["𝔖"] = ("S", "mathfr"),
        ["𝔗"] = ("T", "mathfr"),
        ["𝔘"] = ("U", "mathfr"),
        ["𝔙"] = ("V", "mathfr"),
        ["𝔚"] = ("W", "mathfr"),
        ["𝔛"] = ("X", "mathfr"),
        ["𝔜"] = ("Y", "mathfr"),
        ["ℨ"] = ("Z", "mathfr"),
        ["𝖠"] = ("A", "mathsf"),
        ["Α"] = ("A", "mathsf"),
        ["𝖡"] = ("B", "mathsf"),
        ["Β"] = ("B", "mathsf"),
        ["𝖢"] = ("C", "mathsf"),
        ["𝖣"] = ("D", "mathsf"),
        ["𝖤"] = ("E", "mathsf"),
        ["𝖥"] = ("F", "mathsf"),
        ["𝖦"] = ("G", "mathsf"),
        ["𝖧"] = ("H", "mathsf"),
        ["𝖨"] = ("I", "mathsf"),
        ["𝖩"] = ("J", "mathsf"),
        ["ȷ"] = ("J", "mathsf"),
        ["𝖪"] = ("K", "mathsf"),
        ["Κ"] = ("K", "mathsf"),
        ["𝖫"] = ("L", "mathsf"),
        ["𝖬"] = ("M", "mathsf"),
        ["𝖭"] = ("N", "mathsf"),
        ["𝖮"] = ("O", "mathsf"),
        ["𝖯"] = ("P", "mathsf"),
        ["𝖰"] = ("Q", "mathsf"),
        ["𝖱"] = ("R", "mathsf"),
        ["𝖲"] = ("S", "mathsf"),
        ["𝖳"] = ("T", "mathsf"),
        ["𝖴"] = ("U", "mathsf"),
        ["𝖵"] = ("V", "mathsf"),
        ["𝖶"] = ("W", "mathsf"),
        ["𝖷"] = ("X", "mathsf"),
        ["Χ"] = ("X", "mathsf"),
        ["𝖸"] = ("Y", "mathsf"),
        ["𝖹"] = ("Z", "mathsf"),
        ["𝚨"] = ("A", "mathtt"),
        ["𝚩"] = ("B", "mathtt"),
        ["𝚪"] = ("\\Gamma", "mathtt"),
        ["𝚫"] = ("\\Delta", "mathtt"),
        ["𝚬"] = ("E", "mathtt"),
        ["𝚭"] = ("F", "mathtt"),
        ["𝚮"] = ("G", "mathtt"),
        ["𝚯"] = ("\\Theta", "mathtt"),
        ["𝚰"] = ("I", "mathtt"),
        ["𝚱"] = ("K", "mathtt"),
        ["𝚲"] = ("\\Lambda", "mathtt"),
        ["𝚳"] = ("M", "mathtt"),
        ["𝚴"] = ("N", "mathtt"),
        ["𝚵"] = ("\\Pi", "mathtt"),
        ["𝚶"] = ("O", "mathtt"),
        ["𝚷"] = ("\\Pi", "mathtt"),
        ["𝚸"] = ("Q", "mathtt"),
        ["𝚹"] = ("R", "mathtt"),
        ["𝚺"] = ("S", "mathtt"),
        ["𝚻"] = ("T", "mathtt"),
        ["𝚼"] = ("U", "mathtt"),
        ["𝚽"] = ("\\Phi", "mathtt"),
        ["𝚾"] = ("W", "mathtt"),
        ["𝚿"] = ("\\Psi", "mathtt"),
        ["𝛀"] = ("\\Omega", "mathtt"),
    };
}
